name: Premier Workflow
# Déclencheur : quand exécuter ce workflow ?
# [push] signifie "à chaque push sur n'importe quelle branche"
on:
  push:
    branches: [main]
jobs:
  dire-bonjour:
    runs-on: ubuntu-latest
    steps:
      - name: Etape 1
        run: echo "Bonjour classe ICT324 !"
      - name: Etape 2
        run: echo "Ceci est mon premier workflow automatisé."
      - name: Etape 3